
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyFileVersion("2.8.4.0")]
 [assembly: AssemblyVersion("2.8.4.0")]
 [assembly: KSPAssembly("WaypointManager", 2, 8, 4)]
